#! /bin/csh -f

set port = 7000
if ( "$1" != "" ) set port="$1"

valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --num-callers=40 --track-fds=yes --log-file="valgrind.out" ./swrip $port
